# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=200)),
                ('Correl', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=100)),
                ('Money', models.IntegerField(default=0)),
                ('Subjects', models.CharField(max_length=200)),
                ('Metro', models.CharField(max_length=1000)),
                ('ComeHome', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Feedback', models.IntegerField(default=0)),
                ('SkypeNames', models.BooleanField(default=False)),
                ('RatingSum', models.IntegerField(blank=True, default=0, null=True)),
                ('Rating', models.IntegerField(default=0)),
                ('RatingDivSum', models.FloatField(default=0)),
                ('FeedDivSum', models.FloatField(default=0)),
                ('Funct', models.FloatField(default=0)),
                ('FromSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dopObrazovanieApp.Sites')),
            ],
        ),
    ]
