# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dopObrazovanieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites',
            new_name='Site',
        ),
    ]
